# Pandas

First step is to import pandas so we can begin to work with it.

In [1]:
#first must import library
import pandas as pd
#pd is the usual pd used to shorten pandas
#each time we use pandas use pd.

## Create a DataFrame from a dictionary

Let's create a DataFrame from the following dictionary:

In [2]:
my_dictionary = {'grade': [45, 88, 56, 15, 71],
                   'Name': ['Sam', 'Andrea', 'Alex', 'Robin', 'Kia'],
                   'Age': [14, 25, 55, 8, 21]}

# convert my_dictionary to a DataFrame
#Dataframe = column of data in table
#each row is separated by a comma
#two commas indicate missing data

my_dict_df = pd.DataFrame(my_dictionary)
#take a dictionary, change it to a dataframe

Display the DataFrame we just created. In one cell, call `print(df)`. In another cell, just write the `df` name by itself and run it. Compare the **difference** in their outputs.

In [5]:
print (my_dictionary)
print()
#to easily read
print (my_dict_df)

{'grade': [45, 88, 56, 15, 71], 'Name': ['Sam', 'Andrea', 'Alex', 'Robin', 'Kia'], 'Age': [14, 25, 55, 8, 21]}

   grade    Name  Age
0     45     Sam   14
1     88  Andrea   25
2     56    Alex   55
3     15   Robin    8
4     71     Kia   21

In [ ]:
#when in Jupyter notebook, 
my_dict_df
#if you just write the dataframe name, it highlights the rows

   grade    Name  Age
0     45     Sam   14
1     88  Andrea   25
2     56    Alex   55
3     15   Robin    8
4     71     Kia   21

Use `df.head()` to show the first 5 rows of the DataFrame.

In [10]:
#if you want to extract a first certain of rows
#everthing shown above (table) is now in the variable
#if leave empty, default is the top 5
my_dict_df.head(2)
print()
my_dict_df.tail(2)

   grade   Name  Age
3     15  Robin    8
4     71    Kia   21

 **Note:** `df.head()` shows 5 rows by default, but you can select how many you want to show. For example, 2.

In [ ]:
#QUESTION ABOUT HOW JUPYTER STORES

## Create a DataFrame from a CSV file

If you are on VSCode the `chocolate_sales.csv` should be in the same directory as your current .ipynb file.
If you are using JupyterHub or other online interpreter (e.g. Jupyter.org, Google colab, etc.) you need to upload the `chocolate_sales.csv` in the same directory as your current .ipynb file.

In [ ]:
my_csv_df = pd.read_csv('chocolate_sales.csv')
#exact file name
my_csv_df


#thoughest part of function: analyze the output
#0 to 1093: indexes
#tells you rows and columns
#... is the truncation of the data

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04-Jan-22,5320.0,180
1,Van Tuxwell,India,85% Dark Bars,01-Aug-22,NaN,94
2,Gigi Bohling,India,Peanut Butter Cubes,07-Jul-22,4501.0,91
3,Jan Morforth,Australia,Peanut Butter Cubes,27-Apr-22,12726.0,342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24-Feb-22,13685.0,184
...,...,...,...,...,...,...
1089,Karlen McCaffrey,Australia,Spicy Special Slims,17-May-22,4410.0,323
1090,Jehu Rudeforth,USA,White Choc,07-Jun-22,6559.0,119
1091,Ches Bonnell,Canada,Organic Choco Syrup,26-Jul-22,574.0,217
1092,Dotty Strutley,India,Eclairs,28-Jul-22,2086.0,384
1093,Karlen McCaffrey,India,70% Dark Bites,23-May-22,5075.0,344

## Viewing Data
Use `df.tail()` to display the last 5 rows. This is useful for quickly inspecting the end of large datasets.

In [12]:
my_csv_df.tail()

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
1089,Karlen McCaffrey,Australia,Spicy Special Slims,17-May-22,4410.0,323
1090,Jehu Rudeforth,USA,White Choc,07-Jun-22,6559.0,119
1091,Ches Bonnell,Canada,Organic Choco Syrup,26-Jul-22,574.0,217
1092,Dotty Strutley,India,Eclairs,28-Jul-22,2086.0,384
1093,Karlen McCaffrey,India,70% Dark Bites,23-May-22,5075.0,344

Use `df.sample()` to display a random row.

In [ ]:
my_csv_df.sample(10)
#gives random rows

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
670,Andria Kimpton,New Zealand,Orange Choco,14-Jun-22,8169.0,88
456,Andria Kimpton,Australia,85% Dark Bars,23-Aug-22,4186.0,233
854,Camilla Castle,UK,Mint Chip Choco,26-May-22,4977.0,317
298,Dennison Crosswaite,Canada,Eclairs,15-Mar-22,455.0,45
703,Ches Bonnell,USA,Choco Coated Almonds,04-Jan-22,14525.0,92
781,Oby Sorrel,New Zealand,Spicy Special Slims,03-Jun-22,1617.0,13
1079,Jan Morforth,UK,Baker's Choco Chips,11-Mar-22,721.0,251
732,Jan Morforth,UK,Organic Choco Syrup,12-Apr-22,1197.0,356
74,Van Tuxwell,UK,Organic Choco Syrup,26-Aug-22,2002.0,214
428,Ches Bonnell,UK,White Choc,03-Jan-22,3269.0,226


To show information about columns, non-null counts, and data types, use `df.info()`.

In [ ]:
my_csv_df.info()
#get statistics


#tells types of data (pandas)
#tells index range for the rows
#Tells the number of entries (rows)
#total of columns, and what columns are, with indeces of columns
#1094 non-null = all 1094 rows have a value in column
#1092 says that there are two empty rows
#tells type
#tells what each columns contain

<class 'pandas.DataFrame'>
RangeIndex: 1094 entries, 0 to 1093
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   1094 non-null   str
 1   Country        1094 non-null   str
 2   Product        1094 non-null   str
 3   Date           1094 non-null   str
 4   Amount         1092 non-null   float64
 5   Boxes Shipped  1094 non-null   int64
dtypes: float64(1), int64(1), str(4)
memory usage: 51.4 KB

Get the total number of entries (rows) use `len(df)`

In [18]:
#if just want to get number of rows
len(my_csv_df)

1094

## Summary Statistics

- `df.describe()` shows summary stats for numeric columns and 
- `df.describe(include='all')` shows summary for all columns including non-numeric

try them.

In [21]:
my_csv_df.describe(include = 'all').round(2)
#describe statistcs
# if lots of decimals,
#round stuck at the end to round

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
count,1094,1094,1094,1094,1092.00,1094.00
unique,25,6,22,168,NaN,NaN
top,Kelci Walkden,Australia,50% Dark Bites,13-Jan-22,NaN,NaN
freq,54,205,60,16,NaN,NaN
mean,NaN,NaN,NaN,NaN,5654.86,161.80
std,NaN,NaN,NaN,NaN,4102.81,121.54
min,NaN,NaN,NaN,NaN,7.00,1.00
25%,NaN,NaN,NaN,NaN,2397.50,70.00
50%,NaN,NaN,NaN,NaN,4868.50,135.00
75%,NaN,NaN,NaN,NaN,8032.50,228.75
max,NaN,NaN,NaN,NaN,22050.00,709.00

In [ ]:
#count, give number of entries for each columns
#only give stats only on numbers. Cannot do statistics on texts, but you can force pandas to give six rows with include='all'
#When NaN, no possible statistics operations

## Selecting Data
A **series** is a single column in a dataframe. We can get one `df[column_name]`. Try it for `"Country"` column.

In [23]:
#look at single column, SPELL EXACTLY SAME WAY, copy paste
#PUT THE COLUMN IN A STRING
my_csv_df[['Country']]

        Country
0            UK
1         India
2         India
3     Australia
4            UK
...         ...
1089  Australia
1090        USA
1091     Canada
1092      India
1093      India

[1094 rows x 1 columns]

We can loop over a series. Let's print all the data in the series from previous cell:

In [ ]:
#gives back a series. 
#single is a single column only
#data frame is many dimensions, 
#if two square brackets, output changes

#What do double brackets do???
#single bracket, only one column title, list of all data in column into a 'list'
#double column returns a data frame

I want to loop over the series again and find all the countries that their name starts with `U`.

**Hint:** I need to use conditionals and `string.startswith()`

In [24]:
#When I want the whole thing
#view series like a list
for item in my_csv_df['Country']:
    print(item)

#python treats the dataframe like a value

UK
India
India
Australia
UK
India
UK
Australia
New Zealand
Australia
UK
USA
Canada
New Zealand
New Zealand
Australia
Canada
USA
Canada
UK
Australia
USA
USA
UK
Australia
India
Canada
USA
New Zealand
New Zealand
New Zealand
UK
Australia
UK
Canada
USA
UK
New Zealand
Australia
India
USA
USA
Canada
India
Canada
USA
USA
Australia
India
India
Canada
Australia
Australia
USA
India
Canada
New Zealand
Canada
Australia
Australia
Australia
Australia
Canada
India
India
Australia
Australia
India
India
USA
USA
UK
New Zealand
New Zealand
UK
Canada
USA
USA
UK
USA
USA
Australia
New Zealand
New Zealand
Canada
Australia
USA
Australia
Australia
Canada
UK
India
USA
Australia
Canada
New Zealand
Australia
UK
USA
USA
Australia
USA
India
USA
Canada
New Zealand
UK
USA
India
India
India
UK
Australia
Canada
Australia
Australia
Canada
India
Australia
USA
Canada
Australia
Canada
India
UK
India
UK
New Zealand
Australia
Australia
Canada
Australia
New Zealand
UK
Canada
India
India
India
UK
USA
New Zealand
USA
New Zealand
New Zealand
Australia
New Zealand
New Zealand
Australia
Australia
India
Australia
India
UK
India
UK
India
UK
Australia
Canada
Canada
USA
Canada
New Zealand
Australia
USA
UK
New Zealand
India
New Zealand
Australia
USA
India
UK
Canada
Australia
UK
Australia
India
UK
USA
Australia
Canada
USA
Australia
India
UK
India
UK
New Zealand
UK
Australia
UK
Australia
USA
Canada
USA
New Zealand
UK
India
New Zealand
UK
New Zealand
UK
Australia
Canada
India
Australia
Australia
India
Australia
Canada
USA
UK
New Zealand
Australia
UK
Australia
India
USA
UK
Australia
UK
Australia
India
UK
India
UK
Australia
USA
India
New Zealand
USA
Australia
Canada
Australia
New Zealand
USA
Australia
UK
India
India
USA
UK
Australia
New Zealand
USA
UK
Australia
India
UK
USA
USA
UK
Australia
India
New Zealand
USA
India
Australia
India
New Zealand
UK
Australia
Canada
USA
India
USA
New Zealand
New Zealand
Canada
Australia
Australia
UK
Canada
USA
Canada
Canada
UK
USA
India
India
New Zealand
Australia
UK
Australia
India
UK
Australia
India
USA
USA
Canada
USA
USA
Canada
New Zealand
Australia
UK
Canada
India
New Zealand
Australia
Canada
Australia
New Zealand
USA
Australia
Canada
Australia
USA
Australia
India
UK
Australia
UK
Australia
UK
Canada
USA
India
New Zealand
India
India
New Zealand
Canada
USA
Canada
USA
Australia
New Zealand
Canada
Canada
Australia
Australia
UK
UK
UK
Australia
India
Canada
UK
Canada
USA
India
India
Australia
Australia
UK
Canada
UK
Canada
New Zealand
Australia
New Zealand
New Zealand
India
Australia
Australia
New Zealand
New Zealand
New Zealand
India
UK
Australia
USA
Australia
India
Australia
USA
Canada
UK
UK
USA
India
Australia
USA
Australia
Australia
USA
USA
UK
USA
Canada
India
USA
USA
India
New Zealand
UK
Canada
New Zealand
New Zealand
Australia
Australia
Canada
USA
New Zealand
UK
Canada
New Zealand
USA
USA
New Zealand
India
UK
New Zealand
Canada
USA
India
USA
UK
India
UK
India
Australia
New Zealand
UK
India
New Zealand
New Zealand
New Zealand
UK
Australia
USA
Canada
Canada
New Zealand
India
UK
USA
New Zealand
India
India
India
New Zealand
New Zealand
Canada
USA
India
New Zealand
USA
India
New Zealand
UK
Australia
Australia
USA
Canada
UK
Australia
Canada
USA
Canada
Australia
New Zealand
UK
Australia
Australia
India
USA
Canada
Australia
USA
New Zealand
USA
USA
New Zealand
Canada
UK
USA
USA
Australia
India
New Zealand
India
USA
USA
New Zealand
USA
New Zealand
Canada
New Zealand
USA
Australia
India
UK
USA
Canada
UK
India
Canada
UK
USA
Canada
Australia
New Zealand
UK
USA
USA
New Zealand
New Zealand
USA
India
India
Canada
Australia
UK
USA
Canada
Australia
New Zealand
UK
Australia
Canada
Australia
Australia
UK
Australia
Australia
New Zealand
USA
USA
UK
UK
USA
India
New Zealand
UK
USA
New Zealand
USA
USA
Canada
India
USA
USA
Australia
India
USA
USA
UK
Canada
Canada
India
India
Canada
India
Australia
Australia
USA
New Zealand
UK
USA
New Zealand
USA
USA
Canada
Australia
USA
India
New Zealand
Canada
USA
New Zealand
Australia
Australia
Canada
UK
Australia
India
USA
UK
UK
Canada
Australia
Canada
India
Australia
UK
Canada
USA
India
USA
Canada
Canada
Australia
Canada
Canada
New Zealand
India
New Zealand
New Zealand
New Zealand
UK
USA
New Zealand
India
USA
Australia
Canada
India
USA
Australia
India
New Zealand
USA
India
USA
Australia
Australia
New Zealand
UK
India
UK
USA
New Zealand
USA
New Zealand
India
Australia
USA
Canada
Canada
India
New Zealand
New Zealand
Australia
UK
USA
Canada
India
New Zealand
Australia
USA
India
UK
Australia
Canada
India
India
India
India
UK
USA
Canada
Australia
Australia
Australia
Australia
India
Canada
USA
Canada
New Zealand
New Zealand
Australia
Canada
India
USA
New Zealand
India
Canada
India
India
Australia
Canada
New Zealand
Canada
UK
New Zealand
New Zealand
UK
Canada
UK
UK
UK
USA
UK
New Zealand
Canada
New Zealand
New Zealand
Australia
USA
Australia
New Zealand
USA
New Zealand
UK
USA
UK
New Zealand
USA
Australia
India
USA
Canada
New Zealand
USA
USA
Canada
New Zealand
India
USA
Australia
New Zealand
Australia
New Zealand
Canada
India
Canada
UK
New Zealand
Australia
India
UK
New Zealand
Australia
Canada
India
India
UK
UK
India
UK
Australia
Canada
New Zealand
UK
UK
Australia
New Zealand
UK
Canada
UK
Canada
USA
Canada
UK
UK
Australia
USA
Australia
USA
Canada
Australia
India
Canada
New Zealand
India
Australia
New Zealand
Canada
India
Australia
Canada
UK
New Zealand
Australia
New Zealand
Canada
New Zealand
Australia
Australia
Australia
India
Australia
USA
Canada
Canada
Canada
India
New Zealand
New Zealand
Canada
Australia
India
UK
USA
USA
India
New Zealand
New Zealand
New Zealand
India
India
New Zealand
Australia
New Zealand
New Zealand
Canada
New Zealand
USA
New Zealand
UK
UK
USA
Australia
India
USA
New Zealand
Australia
UK
Canada
UK
New Zealand
India
New Zealand
Canada
New Zealand
Canada
Canada
Canada
UK
New Zealand
UK
UK
New Zealand
USA
UK
USA
Canada
India
Canada
Canada
India
Australia
India
UK
India
UK
Canada
India
Canada
India
Australia
UK
Australia
Australia
India
New Zealand
India
Australia
Canada
India
Canada
Australia
Canada
USA
Canada
USA
New Zealand
Canada
India
UK
USA
Australia
Australia
India
USA
Australia
USA
UK
New Zealand
India
New Zealand
Australia
UK
Canada
Australia
UK
New Zealand
New Zealand
UK
Australia
New Zealand
India
India
UK
UK
UK
Canada
USA
UK
Canada
India
Canada
India
New Zealand
UK
New Zealand
Canada
Australia
New Zealand
UK
UK
India
UK
UK
Canada
UK
UK
UK
New Zealand
Australia
Canada
USA
New Zealand
Australia
New Zealand
New Zealand
UK
Australia
USA
India
USA
India
UK
Australia
USA
India
India
India
Canada
Canada
New Zealand
New Zealand
UK
India
Australia
UK
Canada
India
Canada
UK
India
Canada
India
Canada
Australia
USA
Canada
Australia
India
UK
Australia
Canada
UK
Canada
USA
USA
New Zealand
Canada
Australia
UK
UK
New Zealand
Canada
India
UK
India
USA
India
UK
Australia
India
India
Australia
USA
USA
New Zealand
India
India
India
Australia
New Zealand
Australia
UK
Canada
Australia
Australia
India
UK
New Zealand
USA
UK
New Zealand
New Zealand
Canada
USA
Canada
USA
New Zealand
New Zealand
UK
USA
India
Australia
Australia
Canada
Canada
USA
New Zealand
New Zealand
New Zealand
New Zealand
New Zealand
Australia
UK
Canada
UK
UK
USA
USA
USA
Australia
Canada
USA
UK
Australia
India
Australia
UK
UK
UK
Australia
Canada
UK
Canada
Australia
UK
India
India
New Zealand
India
UK
India
Australia
Canada
Australia
Canada
USA
New Zealand
UK
India
India
India
UK
Australia
India
Canada
India
Australia
USA
UK
UK
USA
Canada
Australia
Canada
India
Australia
USA
Canada
USA
Australia
Canada
New Zealand
Canada
Australia
Canada
Canada
New Zealand
Canada
India
India
Australia
Canada
Canada
UK
UK
USA
USA
New Zealand
India
New Zealand
Canada
India
Australia
Australia
USA
Canada
India
India

## Filtering Data

We can use `df[df[column_name] == 'Value']` to filter data. Now try filtering rows to show `"Sales Person"` whose name is `"Karlen McCaffrey"`.

In [28]:
#print country starting with u
for item in my_csv_df['Country']:
    if item.startswith('U'):
        print(f'{item} starts with U')

UK starts with U
UK starts with U
UK starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
UK starts with U
UK starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
USA starts with U
USA starts with U
USA starts with U
USA starts with U
USA starts with U
UK starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
UK starts with U
USA starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
UK starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
UK starts with U
UK starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
UK starts with U
UK starts with U
USA starts with U
UK starts with U
UK starts with U
USA starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
USA starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
UK starts with U
USA starts with U
UK starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
UK starts with U
USA starts with U
UK starts with U
UK starts with U
USA starts with U
USA starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
UK starts with U
UK starts with U
USA starts with U
USA starts with U
USA starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
USA starts with U
UK starts with U
UK starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
UK starts with U
USA starts with U
USA starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
UK starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
USA starts with U
USA starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
UK starts with U
UK starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
UK starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
UK starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
USA starts with U
USA starts with U
USA starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
USA starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
UK starts with U
UK starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
USA starts with U
USA starts with U
USA starts with U
UK starts with U
UK starts with U
USA starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
UK starts with U
USA starts with U
USA starts with U
USA starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
USA starts with U
USA starts with U
USA starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
USA starts with U
UK starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
USA starts with U
UK starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
USA starts with U
UK starts with U
USA starts with U
UK starts with U
UK starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
USA starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
USA starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
UK starts with U
UK starts with U
UK starts with U
USA starts with U
UK starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
UK starts with U
UK starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
UK starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
USA starts with U
USA starts with U
UK starts with U
UK starts with U
UK starts with U
USA starts with U
USA starts with U
USA starts with U
USA starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
UK starts with U
USA starts with U
UK starts with U
UK starts with U
USA starts with U
UK starts with U
UK starts with U
USA starts with U
USA starts with U
USA starts with U
UK starts with U
UK starts with U
USA starts with U
USA starts with U
USA starts with U

If this syntax looks confusing, don't panic! All we're doing is putting the filter condition inside `df[]`, and we are simply keeping the rows where that condition is true.

In [ ]:
#Karlen repeats multiple times.
#I want to extract only the rows with his name

#One shot way
#1: get into Dataframe.
#which column has name
my_csv_df['Sales Person'] == 'Karlen McCaffrey'
#get false and trues,
#but i want the rows, with data, not booleans

#so:
my_csv_df[my_csv_df['Sales Person'] == 'Karlen McCaffrey']
#double bracket returns dataframe

#now extract data of
#can store
new_df = my_csv_df[my_csv_df['Sales Person'] == 'Karlen McCaffrey']

#why twice mention? make dataframe from list?

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
13,Karlen McCaffrey,New Zealand,Drinking Coco,28-Jul-22,168.0,156
25,Karlen McCaffrey,India,Fruit & Nut Bars,26-Jan-22,168.0,321
33,Karlen McCaffrey,UK,Almond Choco,30-Jun-22,6839.0,133
39,Karlen McCaffrey,India,Manuka Honey Choco,04-Jul-22,2443.0,581
41,Karlen McCaffrey,USA,Raspberry Choco,15-Apr-22,14749.0,354
63,Karlen McCaffrey,India,Almond Choco,06-Jul-22,6090.0,149
86,Karlen McCaffrey,USA,Orange Choco,12-May-22,11095.0,401
94,Karlen McCaffrey,Canada,50% Dark Bites,15-Jul-22,2919.0,65
105,Karlen McCaffrey,New Zealand,70% Dark Bites,02-Aug-22,126.0,40
154,Karlen McCaffrey,UK,Eclairs,25-Jan-22,7798.0,196
159,Karlen McCaffrey,Canada,Smooth Sliky Salty,19-Jan-22,3017.0,184
175,Karlen McCaffrey,UK,Baker's Choco Chips,07-Feb-22,4753.0,389
186,Karlen McCaffrey,India,Drinking Coco,31-May-22,4795.0,233
207,Karlen McCaffrey,Australia,White Choc,05-Jan-22,7357.0,48
210,Karlen McCaffrey,Canada,Eclairs,20-Apr-22,3479.0,358
276,Karlen McCaffrey,Canada,Organic Choco Syrup,15-Jul-22,2415.0,312
278,Karlen McCaffrey,USA,Milk Bars,27-Jan-22,4389.0,7
279,Karlen McCaffrey,India,Orange Choco,27-Jun-22,3122.0,149
284,Karlen McCaffrey,Australia,Almond Choco,08-Jul-22,7294.0,128
299,Karlen McCaffrey,India,Mint Chip Choco,15-Jul-22,10990.0,184
341,Karlen McCaffrey,Canada,Spicy Special Slims,02-Aug-22,6328.0,47
353,Karlen McCaffrey,New Zealand,Fruit & Nut Bars,07-Feb-22,1218.0,135
402,Karlen McCaffrey,New Zealand,Eclairs,06-May-22,2597.0,177
418,Karlen McCaffrey,New Zealand,Caramel Stuffed Bars,31-Jan-22,5334.0,227
449,Karlen McCaffrey,Australia,70% Dark Bites,24-Jun-22,238.0,317
459,Karlen McCaffrey,USA,Drinking Coco,29-Jun-22,112.0,223
462,Karlen McCaffrey,USA,Mint Chip Choco,15-Feb-22,15652.0,53
490,Karlen McCaffrey,Canada,Peanut Butter Cubes,12-Aug-22,3094.0,159
504,Karlen McCaffrey,Canada,Raspberry Choco,09-May-22,651.0,224
515,Karlen McCaffrey,Australia,After Nines,11-Aug-22,2303.0,67
538,Karlen McCaffrey,USA,Manuka Honey Choco,01-Feb-22,10171.0,67
604,Karlen McCaffrey,New Zealand,Baker's Choco Chips,05-Apr-22,5012.0,189
618,Karlen McCaffrey,India,85% Dark Bars,30-Mar-22,945.0,83
654,Karlen McCaffrey,New Zealand,85% Dark Bars,28-Jun-22,6069.0,55
719,Karlen McCaffrey,India,White Choc,17-Jan-22,7483.0,232
730,Karlen McCaffrey,Australia,50% Dark Bites,17-Jan-22,6678.0,708
769,Karlen McCaffrey,Canada,70% Dark Bites,24-Jun-22,7714.0,597
817,Karlen McCaffrey,New Zealand,Mint Chip Choco,02-Mar-22,4326.0,61
836,Karlen McCaffrey,UK,50% Dark Bites,06-Apr-22,3647.0,310
848,Karlen McCaffrey,USA,Eclairs,15-Aug-22,868.0,125
849,Karlen McCaffrey,Canada,Fruit & Nut Bars,02-Jun-22,210.0,16
952,Karlen McCaffrey,Canada,Caramel Stuffed Bars,02-Mar-22,3346.0,304
974,Karlen McCaffrey,Australia,Raspberry Choco,23-Aug-22,994.0,57
1007,Karlen McCaffrey,Australia,99% Dark & Pure,26-Jan-22,10822.0,168
1013,Karlen McCaffrey,USA,White Choc,24-Aug-22,4592.0,2
1089,Karlen McCaffrey,Australia,Spicy Special Slims,17-May-22,4410.0,323
1093,Karlen McCaffrey,India,70% Dark Bites,23-May-22,5075.0,344

In [ ]:
#other method

person_condition_filter = my_csv_df['Sales Person'] == 'Karlen McCaffrey'

my_csv_df[person_condition_filter]

#make a new dataframe with list and make that list into a dataframe

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
13,Karlen McCaffrey,New Zealand,Drinking Coco,28-Jul-22,168.0,156
25,Karlen McCaffrey,India,Fruit & Nut Bars,26-Jan-22,168.0,321
33,Karlen McCaffrey,UK,Almond Choco,30-Jun-22,6839.0,133
39,Karlen McCaffrey,India,Manuka Honey Choco,04-Jul-22,2443.0,581
41,Karlen McCaffrey,USA,Raspberry Choco,15-Apr-22,14749.0,354
63,Karlen McCaffrey,India,Almond Choco,06-Jul-22,6090.0,149
86,Karlen McCaffrey,USA,Orange Choco,12-May-22,11095.0,401
94,Karlen McCaffrey,Canada,50% Dark Bites,15-Jul-22,2919.0,65
105,Karlen McCaffrey,New Zealand,70% Dark Bites,02-Aug-22,126.0,40
154,Karlen McCaffrey,UK,Eclairs,25-Jan-22,7798.0,196
159,Karlen McCaffrey,Canada,Smooth Sliky Salty,19-Jan-22,3017.0,184
175,Karlen McCaffrey,UK,Baker's Choco Chips,07-Feb-22,4753.0,389
186,Karlen McCaffrey,India,Drinking Coco,31-May-22,4795.0,233
207,Karlen McCaffrey,Australia,White Choc,05-Jan-22,7357.0,48
210,Karlen McCaffrey,Canada,Eclairs,20-Apr-22,3479.0,358
276,Karlen McCaffrey,Canada,Organic Choco Syrup,15-Jul-22,2415.0,312
278,Karlen McCaffrey,USA,Milk Bars,27-Jan-22,4389.0,7
279,Karlen McCaffrey,India,Orange Choco,27-Jun-22,3122.0,149
284,Karlen McCaffrey,Australia,Almond Choco,08-Jul-22,7294.0,128
299,Karlen McCaffrey,India,Mint Chip Choco,15-Jul-22,10990.0,184
341,Karlen McCaffrey,Canada,Spicy Special Slims,02-Aug-22,6328.0,47
353,Karlen McCaffrey,New Zealand,Fruit & Nut Bars,07-Feb-22,1218.0,135
402,Karlen McCaffrey,New Zealand,Eclairs,06-May-22,2597.0,177
418,Karlen McCaffrey,New Zealand,Caramel Stuffed Bars,31-Jan-22,5334.0,227
449,Karlen McCaffrey,Australia,70% Dark Bites,24-Jun-22,238.0,317
459,Karlen McCaffrey,USA,Drinking Coco,29-Jun-22,112.0,223
462,Karlen McCaffrey,USA,Mint Chip Choco,15-Feb-22,15652.0,53
490,Karlen McCaffrey,Canada,Peanut Butter Cubes,12-Aug-22,3094.0,159
504,Karlen McCaffrey,Canada,Raspberry Choco,09-May-22,651.0,224
515,Karlen McCaffrey,Australia,After Nines,11-Aug-22,2303.0,67
538,Karlen McCaffrey,USA,Manuka Honey Choco,01-Feb-22,10171.0,67
604,Karlen McCaffrey,New Zealand,Baker's Choco Chips,05-Apr-22,5012.0,189
618,Karlen McCaffrey,India,85% Dark Bars,30-Mar-22,945.0,83
654,Karlen McCaffrey,New Zealand,85% Dark Bars,28-Jun-22,6069.0,55
719,Karlen McCaffrey,India,White Choc,17-Jan-22,7483.0,232
730,Karlen McCaffrey,Australia,50% Dark Bites,17-Jan-22,6678.0,708
769,Karlen McCaffrey,Canada,70% Dark Bites,24-Jun-22,7714.0,597
817,Karlen McCaffrey,New Zealand,Mint Chip Choco,02-Mar-22,4326.0,61
836,Karlen McCaffrey,UK,50% Dark Bites,06-Apr-22,3647.0,310
848,Karlen McCaffrey,USA,Eclairs,15-Aug-22,868.0,125
849,Karlen McCaffrey,Canada,Fruit & Nut Bars,02-Jun-22,210.0,16
952,Karlen McCaffrey,Canada,Caramel Stuffed Bars,02-Mar-22,3346.0,304
974,Karlen McCaffrey,Australia,Raspberry Choco,23-Aug-22,994.0,57
1007,Karlen McCaffrey,Australia,99% Dark & Pure,26-Jan-22,10822.0,168
1013,Karlen McCaffrey,USA,White Choc,24-Aug-22,4592.0,2
1089,Karlen McCaffrey,Australia,Spicy Special Slims,17-May-22,4410.0,323
1093,Karlen McCaffrey,India,70% Dark Bites,23-May-22,5075.0,344

Filter rows to show values of `"Boxes Shipped"` that are greater than 600.

In [ ]:
# 2-step solution
greater600 = my_csv_df['Boxes Shipped'] >= 600
boxes_df = my_csv_df[greater600]
boxes_df


# 1-step solution
boxes_df2 = my_csv_df[my_csv_df['Boxes Shipped'] >= 600]
boxes_df2

#so make a dataframe with a filter

#overwrite

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
730,Karlen McCaffrey,Australia,50% Dark Bites,17-Jan-22,6678.0,708
852,Marney O'Breen,Canada,Caramel Stuffed Bars,23-Feb-22,1372.0,614
1028,Van Tuxwell,Canada,Drinking Coco,15-Jun-22,4900.0,709

## Statistics and Values
For numeric values, we can get properties like `df[column_name].sum()`, `df[column_name].mean()`, `df[column_name].median()`, `df[column_name].max()`, and `df[column_name].min()` 

Try them all.

In [38]:
print(my_csv_df['Boxes Shipped'].mean().round())

#when print when not print

162.0

In [ ]:
print(my_csv_df['Boxes Shipped'].sum())

#same story for other statistical tool

177007

Find the most frequent `"Product"` using `df[column_name].value_counts()`

In [ ]:
#I want to know how many different products I have
#We have different types of products and number of times it appears

my_csv_df['Product'].value_counts()
#it is sorting in decreasing order!

Product
50% Dark Bites          60
Eclairs                 60
Smooth Sliky Salty      59
White Choc              58
Drinking Coco           56
Spicy Special Slims     54
Organic Choco Syrup     52
85% Dark Bars           50
After Nines             50
Fruit & Nut Bars        50
Peanut Butter Cubes     49
99% Dark & Pure         49
Milk Bars               49
Almond Choco            48
Raspberry Choco         48
Orange Choco            47
Mint Chip Choco         45
Manuka Honey Choco      45
Caramel Stuffed Bars    43
70% Dark Bites          42
Baker's Choco Chips     41
Choco Coated Almonds    39
Name: count, dtype: int64

Get count of non-null values per coulumn using `df.count()`

In [ ]:
my_csv_df.count()
#not on a single column, general on entire Dataframe
#gives statistics (like from info)<
#to be more explicit
my_csv_df['Sales Person'].count()
#np.int64(1094), 1094 is the number interested in

np.int64(1094)

Get Count of non-null values in `"Sales Person"` using `df[column_name].count()`

or for a single series to describe.

## Slicing

Beside using `df.head()` and `df.tail()`, we can slice a series to get the first n rows by `df[column_name][:n]` or `df[column_name][n:]` to get the nth row onward.

Get the first 3 rows of the `"Date"` column.

In [ ]:
my_csv_df['Date']

#Now I just want the first three rows
my_csv_df['Date'][:3]

0    04-Jan-22
2    07-Jul-22
3    27-Apr-22
Name: Date, dtype: str

## Make a smaller DataFrame

If the dataset very large we can obtain a smaller DataFrame and store it in a varible for convenience `smaller_df = df[['col1', 'col2', …]]`
Late we can use it as a regular DaftaFrame.

**Note:** We used two square brackets.

Create a smaller datafarme with only "Product" and "Amount" columns and disply the fisrt 3 rows.

In [46]:
#new_df = my_csv_df['Amount', 'Product']
#error because single braquet is a series. only one columns
new_df = my_csv_df[['Amount', 'Product']]
new_df

       Amount              Product
0      5320.0      Mint Chip Choco
1         NaN        85% Dark Bars
2      4501.0  Peanut Butter Cubes
3     12726.0  Peanut Butter Cubes
4     13685.0  Peanut Butter Cubes
...       ...                  ...
1089   4410.0  Spicy Special Slims
1090   6559.0           White Choc
1091    574.0  Organic Choco Syrup
1092   2086.0              Eclairs
1093   5075.0       70% Dark Bites

[1094 rows x 2 columns]

## Data Cleaning
Drop empty rows with empty values using `df.dropna(inplace = True)`

In [ ]:
#my_csv_df.info()
#amount has 2 empty rows
my_csv_df.dropna(inplace = True)
#inpalce = True: changing the dataframe
my_csv_df.info()
#everything changed to 1092, removed it from the dataframe

<class 'pandas.DataFrame'>
Index: 1092 entries, 0 to 1093
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   1092 non-null   str
 1   Country        1092 non-null   str
 2   Product        1092 non-null   str
 3   Date           1092 non-null   str
 4   Amount         1092 non-null   float64
 5   Boxes Shipped  1092 non-null   int64
dtypes: float64(1), int64(1), str(4)
memory usage: 59.7 KB